export { CATEGORIES, getCategoryInfo } from './categories'
export type { CategoryInfo } from './categories'
export { COLOMBIA_CITIES, DEFAULT_CITY, getCityById } from './cities'
export type { City } from './cities'
export { VEHICLE_TYPES } from './vehicles'
export type { VehicleInfo } from './vehicles'
